#!/usr/bin/env python3
"""
render.py -- turn a campaign Markdown file into a print-ready, "aged tabletop manuscript" PDF.

This is an optional companion tool for the World Architect + One-Shot Campaign Builder.
Point it at any Markdown campaign (for example, one generated by the framework) and it
produces a two-column, parchment-styled PDF with a cover page, read-aloud boxes, styled
tables, and page numbers.

Markdown conventions it understands:
  # Title            -> used only as the document title (rendered on the cover, then skipped)
  ## Section         -> full-width section header
  ### Subsection     -> in-column subheader
  #### Entry         -> a bordered "card" (great for NPCs / locations / items)
  > read-aloud       -> a boxed, italic "read-aloud / boxed text" block
  | tables |         -> styled; tables outside a card span the full page width
  **bold** _italic_  -> inline emphasis (bold is tinted with the theme accent)

Usage:
  python render.py campaign.md -o campaign.pdf --title "The Ethereal" \
      --subtitle "Drowned Light & Borrowed Souls" --theme maroon \
      --footer "A GM-Ready One-Shot"

Requires: markdown, weasyprint, beautifulsoup4, pypdf, reportlab  (see requirements.txt)
For the intended typography, install the free TeX Gyre Bonum / URW Bookman fonts; the
renderer falls back to Georgia/serif if they are absent.
"""
import argparse, io, sys
from pathlib import Path

import markdown
from bs4 import BeautifulSoup
from weasyprint import HTML, CSS
from pypdf import PdfReader, PdfWriter
from reportlab.pdfgen import canvas

THEMES = {
    # accent = headers/labels; rule = gold divider lines; cover = cover background
    "maroon": {"accent": "#58180d", "rule": "#c9a227", "cover": "#58180d"},
    "rust":   {"accent": "#6e2f14", "rule": "#c9a227", "cover": "#6e2f14"},
    "slate":  {"accent": "#26343f", "rule": "#9fb1bd", "cover": "#26343f"},
    "forest": {"accent": "#234023", "rule": "#c9a227", "cover": "#234023"},
    "ink":    {"accent": "#2a2a2a", "rule": "#b08d57", "cover": "#1e1e1e"},
}

_MD = markdown.Markdown(extensions=["tables", "sane_lists"])


def md2html(text: str) -> str:
    _MD.reset()
    return _MD.convert(text.strip())


def parse_nodes(raw: str):
    """Split Markdown into a flat list of heading nodes with their body text."""
    nodes, cur = [], None
    for line in raw.split("\n"):
        import re
        m = re.match(r"^(#{1,4})\s+(.*)$", line)
        if m:
            cur = {"level": len(m.group(1)), "title": m.group(2).strip(), "body": []}
            nodes.append(cur)
        else:
            if cur is None:
                cur = {"level": 0, "title": None, "body": []}
                nodes.append(cur)
            cur["body"].append(line)
    return nodes


def render_node(n) -> str:
    import html as _h
    body = md2html("\n".join(n["body"])) if any(s.strip() for s in n["body"]) else ""
    lvl = n["level"]
    if lvl in (0, 1):
        return f'<div class="prose">{body}</div>' if body else ""
    if lvl == 2:
        return f'<h2 class="section">{_h.escape(n["title"])}</h2>' + (f'<div class="prose">{body}</div>' if body else "")
    if lvl == 3:
        return f'<h3 class="subsection">{_h.escape(n["title"])}</h3>' + (f'<div class="prose">{body}</div>' if body else "")
    return f'<section class="itemcard"><h4>{_h.escape(n["title"])}</h4>{body}</section>'


def postprocess(html_text: str) -> str:
    """Mark tables that are not inside a card so they span both columns."""
    soup = BeautifulSoup(html_text, "html.parser")
    for tbl in soup.find_all("table"):
        if tbl.find_parent("section", class_="itemcard") is None:
            cls = tbl.get("class", [])
            cls.append("fulltable")
            tbl["class"] = cls
    return str(soup)


def build_css(theme: dict, running_header: str) -> str:
    a, r, cov = theme["accent"], theme["rule"], theme["cover"]
    return f"""
@page {{ size: Letter; margin: 16mm 14mm 18mm 14mm; background: #f4e9d2;
  @bottom-center {{ content: ""; }}
  @top-center {{ content: "{running_header}"; font-family:"TeX Gyre Bonum",serif;
    font-variant: small-caps; letter-spacing:.08em; font-size:8.5pt; color:#9a6b3f; }} }}
@page cover {{ margin:0; background:{cov}; @top-center{{content:"";}} @bottom-center{{content:"";}} }}
body {{ font-family:"TeX Gyre Bonum","URW Bookman","Georgia",serif; font-size:9pt; line-height:1.32; color:#1a1208; }}

.cover {{ page:cover; height:100vh; overflow:hidden; color:#f4e9d2; text-align:center;
  display:flex; flex-direction:column; justify-content:center; align-items:center; }}
.cover .frame {{ border:3px double #d9b779; margin:14mm; padding:20mm 10mm; width:100%; box-sizing:border-box; }}
.cover h1 {{ font-size:38pt; margin:0; color:#f0d9a8; font-variant:small-caps; letter-spacing:.03em; line-height:1.03; }}
.cover .sub {{ font-size:14pt; color:#d9b779; margin-top:6mm; font-variant:small-caps; letter-spacing:.14em; }}
.cover .orn {{ font-size:26pt; color:#d9b779; margin:6mm 0; }}
.cover .note {{ margin-top:6mm; font-size:11pt; color:#cda978; font-style:italic; }}
.cover .foot {{ position:absolute; bottom:18mm; left:0; right:0; font-size:9pt; color:#cda978; font-variant:small-caps; letter-spacing:.1em; }}

.columns {{ column-count:2; column-gap:7mm; column-fill:auto; }}
h2.section {{ column-span:all; font-size:19pt; color:{a}; font-variant:small-caps; text-align:center;
  border-bottom:2px solid {r}; padding-bottom:1.5mm; margin:6mm 0 3mm; letter-spacing:.03em; }}
h3.subsection {{ font-size:12.5pt; color:{a}; font-variant:small-caps; border-bottom:1px solid {r};
  margin:3mm 0 1.5mm; padding-bottom:.5mm; break-after:avoid; }}
.prose p {{ margin:0 0 1.8mm; text-align:justify; }}
.prose strong {{ color:{a}; }}
.prose ul, .prose ol {{ margin:1mm 0 2mm 4mm; }} .prose li {{ margin:0 0 1mm; text-align:justify; }}

.itemcard {{ background:#fdf3e0; border:1px solid #d9c7a3; border-top:2.5px solid {a}; border-bottom:2.5px solid {a};
  padding:2.4mm 3mm 3mm; margin:0 0 4mm; break-inside:avoid; }}
.itemcard h4 {{ color:{a}; font-variant:small-caps; font-size:12pt; margin:0 0 .8mm; line-height:1.06; }}
.itemcard p {{ margin:0 0 1.4mm; }} .itemcard strong {{ color:{a}; }}

blockquote {{ background:#f3e3c4; border-left:4px solid {a}; margin:2.4mm 0 3mm; padding:2.2mm 4mm;
  font-style:italic; color:#3a2c14; break-inside:avoid; }}
blockquote p {{ margin:0 0 1.8mm; text-align:justify; }} blockquote p:last-child {{ margin-bottom:0; }}
blockquote strong {{ color:{a}; font-style:normal; }}

table {{ width:100%; border-collapse:collapse; font-size:7.8pt; margin:1.6mm 0; background:#f6e7c8; }}
th {{ color:{a}; font-variant:small-caps; font-size:7pt; border-bottom:1px solid {r}; padding:1mm 1.2mm; text-align:left; }}
td {{ padding:.8mm 1.2mm; border-top:1px solid #e3d2ad; vertical-align:top; }}
th[colspan] {{ text-align:center; background:#efdcb6; color:#7a5230; }}
table.fulltable {{ column-span:all; font-size:8.2pt; }}
"""


def document(inner: str) -> str:
    return "<!DOCTYPE html><html><head><meta charset='utf-8'></head><body>" + inner + "</body></html>"


def make_cover(title, subtitle, note, footer) -> str:
    import html as _h
    parts = ['<div class="cover"><div class="frame">', '<div class="orn">&#10070;</div>',
             f'<h1>{_h.escape(title)}</h1>']
    if subtitle:
        parts.append(f'<div class="sub">{_h.escape(subtitle)}</div>')
    parts.append('<div class="orn">&#10070;</div>')
    if note:
        parts.append(f'<div class="note">{_h.escape(note)}</div>')
    parts.append('</div>')
    if footer:
        parts.append(f'<div class="foot">{_h.escape(footer)}</div>')
    parts.append('</div>')
    return "".join(parts)


def main(argv=None):
    ap = argparse.ArgumentParser(description="Render a campaign Markdown file into a styled PDF.")
    ap.add_argument("input", help="path to the campaign .md file")
    ap.add_argument("-o", "--output", help="output .pdf path (default: alongside input)")
    ap.add_argument("--title", help="cover title (default: first '# ' heading, else file name)")
    ap.add_argument("--subtitle", default="", help="cover subtitle")
    ap.add_argument("--note", default="A GM-Ready One-Shot", help="italic line under the title")
    ap.add_argument("--footer", default="", help="small line at the bottom of the cover")
    ap.add_argument("--theme", default="maroon", choices=sorted(THEMES), help="color theme")
    ap.add_argument("--running-header", help="text in the top margin (default: the title)")
    ap.add_argument("--no-cover", action="store_true", help="skip the cover page")
    args = ap.parse_args(argv)

    src = Path(args.input)
    raw = src.read_text(encoding="utf-8")
    nodes = parse_nodes(raw)

    title = args.title
    if not title:
        h1 = next((n["title"] for n in nodes if n["level"] == 1), None)
        title = h1 or src.stem.replace("_", " ").replace("-", " ").title()
    running = args.running_header or title
    out = Path(args.output) if args.output else src.with_suffix(".pdf")

    css = CSS(string=build_css(THEMES[args.theme], running))

    # content starts at the first '## ' section (or the top if none)
    start = next((i for i, n in enumerate(nodes) if n["level"] == 2), 0)
    content_html = postprocess("\n".join(render_node(n) for n in nodes[start:]))
    content_body = f'<div class="columns">{content_html}</div>'

    writer = PdfWriter()
    if not args.no_cover:
        cover_pdf = HTML(string=document(make_cover(title, args.subtitle, args.note, args.footer))).write_pdf(stylesheets=[css])
        for p in PdfReader(io.BytesIO(cover_pdf)).pages:
            writer.add_page(p)
    content_pdf = HTML(string=document(content_body)).write_pdf(stylesheets=[css])
    for p in PdfReader(io.BytesIO(content_pdf)).pages:
        writer.add_page(p)

    # stamp page numbers (skip the cover)
    accent = THEMES[args.theme]["accent"].lstrip("#")
    rgb = tuple(int(accent[i:i+2], 16) / 255 for i in (0, 2, 4))
    skip_first = not args.no_cover
    for i, page in enumerate(writer.pages):
        if skip_first and i == 0:
            continue
        w = float(page.mediabox.width); h = float(page.mediabox.height)
        buf = io.BytesIO(); cv = canvas.Canvas(buf, pagesize=(w, h))
        cv.setFillColorRGB(*rgb); cv.setFont("Times-Roman", 9)
        cv.drawCentredString(w / 2, 26, str(i + 1)); cv.save(); buf.seek(0)
        page.merge_page(PdfReader(buf).pages[0])

    writer.add_metadata({"/Title": title, "/Subject": args.subtitle})
    with open(out, "wb") as f:
        writer.write(f)
    print(f"Wrote {out} ({len(writer.pages)} pages, theme={args.theme}).")


if __name__ == "__main__":
    main()
